#!/bin/bash

heredir=$(pwd)
envdir=$heredir/xdata/webenv

function setup_python_virtenv() {
   if [ ! -d $envdir ]; then
      mkdir -p $envdir
   fi
   cd $envdir
   virtualenv .
   cd $heredir
}

function install_requirements() {
   local fnreq=$heredir/xdata/requirements.txt

   echo "# This file is autogenerated" > $fnreq
   echo "Genshi>=0.6" >> $fnreq
   echo "setuptools>=0.6" >> $fnreq
   echo "Pygments" >> $fnreq
   echo "pytz" >> $fnreq
   echo "trac==1.0.12" >> $fnreq
   cd $envdir
   source $envdir/bin/activate
   pip install -r $fnreq
   cd $heredir
}

function setup() {
   setup_python_virtenv
   install_requirements
}

setup
